name: gtau_app_front
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  http: 0.13.6
  geolocator: 10.1.0
  google_maps_flutter: 2.5.0
  geojson: ^1.0.0
  intl: any
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.7
  universal_html: ^2.2.3
  image_cropper: ^4.0.1
  image_picker: ^1.0.2
  gallery_image_viewer: ^1.2.0
  path_provider: ^2.1.0
  flutter_image_compress: ^2.0.4
  hive:
  hive_flutter:
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.2
  flutter_keyboard_visibility: ^5.4.1
  scroll_to_index: ^3.0.1
  searchfield: ^0.8.7
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  file_picker: ^6.1.1
  url_launcher: ^6.2.2
  flutter_secure_storage: 9.0.0
  flutter_native_splash: 2.3.7
  web_socket_channel: 2.4.0
  loading_animation_widget: 1.2.0+4
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.web
    - .env.mobile
    - lib/assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
